### ISSUE TITLE
indexOf semver

### ISSUE THREAD

**Issue by mdreizin** [redhivesoftware/math-expression-evaluator#3]
@ankit31894 Last commit `indexOf` broke a lot of projects.

Now it works, but I would suggest you to use for instance [`lodash.indexof`](https://www.npmjs.com/package/lodash.indexof) instead of your patched code, because this code is well tested.

Please be more semver compatible.

**Comment by ankit31894** [comment]
I was going to use underscore but now seeing the lightweight of your proposed method, I have added this to the repo and removed the polyfill code. Thanks
