### ISSUE TITLE
Consider dropping `lodash.indexOf`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [redhivesoftware/math-expression-evaluator#4]
It'd be a major bump, but it'd make `math-expression-evaluator` free of dependencies.

**Comment by ankitbug94** [comment]
Yeah! you are right. It is very easy to implement. But right now I am very busy, would you mind to make the necessarry changes [here](https://github.com/redhivesoftware/math-expression-evaluator/blob/master/src/lexer.js#L2)

**Comment by wtgtybhertgeghgtwtg** [comment]
PR: #5.
